# pylint: disable=invalid-name

'''
Migration File
'''

# Generated by Django 3.2.16 on 2024-02-01 11:58
import django.core.validators
from django.db import migrations, models
import django.utils.timezone

import app_1.manager



class Migration(migrations.Migration):
    '''
    Migration Class
    '''
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),

                ('password', models.CharField(
                    max_length=128,
                    verbose_name='password'
                )),

                ('last_login', models.DateTimeField(
                    blank=True,
                    null=True,
                    verbose_name='last login'
                )),

                ('is_superuser', models.BooleanField(
                    default=False,
                    help_text='all permissions without explicitly assigning them.',
                    verbose_name='superuser status'
                )),

                ('is_staff', models.BooleanField(
                    default=False,
                    help_text='Designates whether the user can log into this admin site.',
                    verbose_name='staff status'
                )),

                ('is_active', models.BooleanField(
                    default=True,
                    help_text='Designates whether this user should be treated as active.',
                    verbose_name='active')),

                ('date_joined', models.DateTimeField(
                    default=django.utils.timezone.now,
                    verbose_name='date joined'
                )),

                ('username', models.CharField(
                    default='user',
                    max_length=50,
                    unique=True
                )),

                ('first_name', models.CharField(
                    blank=True,
                    max_length=50,
                    null=True
                )),

                ('last_name', models.CharField(
                    blank=True,
                    max_length=50,
                    null=True
                )),

                ('email', models.EmailField(
                    blank=True,
                    max_length=254,
                    null=True,
                    unique=True,
                    validators=[django.core.validators.EmailValidator()]
                )),

                ('date_of_birth', models.DateField(
                    blank=True,
                    null=True
                )),

                ('rid', models.CharField(
                    blank=True,
                    max_length=6,
                    null=True,
                    unique=True
                )),

                ('is_verified', models.BooleanField(default=False)),

                ('groups', models.ManyToManyField(
                    blank=True,
                    help_text='The groups this user belongs to.',
                    related_name='user_set',
                    related_query_name='user',
                    to='auth.Group',
                    verbose_name='groups'
                )),

                ('user_permissions', models.ManyToManyField(
                    blank=True,
                    help_text='Specific permissions for this user.',
                    related_name='user_set',
                    related_query_name='user',
                    to='auth.Permission',
                    verbose_name='user permissions'
                )),

            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', app_1.manager.UserManager()),
            ],
        ),
    ]
