# Generated by Django 5.0.1 on 2024-02-02 06:20
'''
Migration File
'''
from django.db import migrations, models


class Migration(migrations.Migration):
    '''
    Migration Class
    '''
    dependencies = [
        ('app_1', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
