'''
Migration File

'''
# Generated by Django 5.0.1 on 2024-02-02 06:53

import app_1.encrypt
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    '''
    Migration Class
    '''
    dependencies = [
        ('app_1', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=app_1.encrypt.EncryptedEmailField(
                default=None,
                max_length=50,
                unique=True,
                validators=[django.core.validators.EmailValidator()
            ]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
