# Generated by Django 5.0.1 on 2024-02-02 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=50, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
