'''
Migration File
'''
# Generated by Django 5.0.1 on 2024-02-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    '''
    Migration Class
    '''

    dependencies = [
        ('app_1', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photo', upload_to=''),
        ),
    ]
