'''
Migration File
'''
# Generated by Django 5.0.1 on 2024-02-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    '''
    Migration Class
    '''
    dependencies = [
        ('app_1', '0010_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/user icon.png', upload_to=''),
        ),
    ]
