# Generated by Django 5.0.1 on 2024-02-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/user_icon.png', upload_to='pictures/'),
        ),
    ]
