# Generated by Django 5.0.1 on 2024-02-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0013_alter_user_groups_alter_user_is_active_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
