# Generated by Django 5.0.1 on 2024-02-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0014_remove_user_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
